config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
  	resources :reviews, only: [ :new, :create ]
  end	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :reviews, dependent: :destroy
	CATEGORY = ['chinese', 'italian', 'japanese', 'french', 'belgian'].freeze
	validates :name, :address, :category, presence: true
	validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = [0, 1, 2, 3, 4, 5].freeze
  belongs_to :restaurant 
  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: RATING }, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
  	@restaurants = Restaurant.all
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  end

  def new
  	@restaurant = Restaurant.new
  end

  def create
	@restaurant = Restaurant.new(reastaurant_params)
	@restaurant.save

	redirect_to restaurant_path(@restaurant)
  end	

  def edit
	@restaurant = Restaurant.find(params[:id]) 	 
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end   

  def destroy 
    @restaurant = Restaurant.find(params[:id])
	@restaurant.destroy

	redirect_to restaurant_path
  end

  def restaurant_params
  	params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def new
  @restaurant = Restaurant.find(params[:restaurant_id])
  @review = Review.new
end

def create
  @restaurant = Restaurant.find(params[:restaurant_id])
  @review = Review.new(review_params)
  @reveiw.restaurant = @restaurant
  @review.save
  redirect_to restaurant_path(@restaurant)
end

private

def review_params
  params.require(:review).permit(:content)
end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>All Restaurants</h1>
  <div>
  	<% @restaurants.each do |restaurant| %>
    <p><%= link_to restaurant.name.capitalize, restaurant_path(restaurant) %></p>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class = "container">
<h1>
  <%= @restaurant.name.capitalize %>
</h1>
<small>
  <%= link_to "Delete", restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" } %>
</small>

<ul>
  <li> <strong><%= @restaurant.address&.capitalize %></strong></li>
  <li> <%= @restaurant.category&.capitalize %></li>	
</ul>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Leave a comment</h1>
  <%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  
  <%= f.submit %>
<% end %>
	
</div>

app/views/reviews/show.html.erb
<div class="container">
  <h1>Reviews</h1>
  <%= link to 'Leave a review', new_restaurant_review_path(@restaurent) %>
  <% @restaurants.reviews.each do |review| %>
    <div>
      <%= review.content %>
      <%= link to 'Delete the review', review_path(review),
      method: :delete %>
    </div>
</div>